export const QUERY_SELECTOR_PARSE_OBSERVER = "#subtotalsSection,#checkoutDisplayPage,.MusicCartReviewButtonSection";
export const QUERY_SELECTOR_MOON_BUTTON = "#order-summary-box .a-box-inner,#subtotals .a-box-inner,.MusicCartReviewButtonSection .a-box-inner,#unifiedPrice_feature_div,#mediaPrice_feature_div";
export const QUERY_SELECTOR_CART_AMOUNT = "input[name='purchaseTotal'][value],#subtotals .a-color-price,#bottomsubtotals .a-color-price,.MusicCartReviewSubtotalSection span.a-color-price, .grand-total-price";
export const QUERY_SELECTOR_CART_CURRENCY = "input[name='purchaseTotalCurrency'][value]";
export const QUERY_SELECTOR_PRODUCT_TITLE = "#productTitle";
export const QUERY_SELECTOR_PRODUCT_IMAGE = "#landingImage";
export const QUERY_SELECTOR_ADD_TO_CART_BUTTON = "#add-to-cart-button";
export const QUERY_SELECTOR_PRODUCT_PRICE = "#priceblock_ourprice,#priceblock_dealprice";
export const QUERY_SELECTOR_PRODUCT_OBSERVER = `#desktop_unifiedPrice,${QUERY_SELECTOR_PRODUCT_TITLE},${QUERY_SELECTOR_PRODUCT_IMAGE},${QUERY_SELECTOR_PRODUCT_PRICE}`;
export const QUERY_SELECTOR_SHIPPING_ADDRESS_SELECT = "#payChangeButtonId,#address-list .a-button-input,#subtotals .a-button-input";
export const QUERY_SELECTOR_BILLING_ADDRESS_SELECT = "#payChangeButtonId,#address-list .a-button-input,#subtotals .a-button-input";
export const QUERY_SELECTOR_PAYMENT_METHOD_SELECT = "#continue-top,#spcViewButtonId,#subtotals .a-button-input";
export const QUERY_SELECTOR_GIFT_OPTIONS_SELECT = "#giftForm .save-gift-button-box input";
